<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<!-- Kopiert den gesamten Ordner "Assets" inklusive Unterordner als physische Dateien -->
		<Content Include="Assets\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>

		<!-- Kopiert den gesamten Ordner "Data\Sets" inklusive Unterordner als physische Dateien -->
		<Content Include="Data\Sets\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>

		<Content Include="Data\Decks\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Data\SaveGames\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Data\Decks\" />
	  <Folder Include="Data\SaveGames\" />
	</ItemGroup>

</Project>